import { invoke } from "@tauri-apps/api/core";
import type {
  ChatGptStatus,
  DeviceCode,
  DescriptionDraft,
  ImageInfo,
  InputImage,
  Preset,
  ProviderConfig,
  ProxySettings,
  SettingsDocument,
  SaveRequest,
  SuperGrokStatus,
  VisionCapabilities,
  VisionModel,
} from "./contracts";

export const commands = {
  health: (): Promise<string> => invoke<string>("health"),
  inspectImage: (input: InputImage): Promise<ImageInfo> => invoke<ImageInfo>("inspect_image", { input }),
  describeImage: (input: InputImage, provider: ProviderConfig, preset: Preset): Promise<DescriptionDraft> =>
    invoke<DescriptionDraft>("describe_image", { input, provider, preset }),
  cancelDescription: (): Promise<void> => invoke<void>("cancel_description"),
  listPresets: (): Promise<readonly Preset[]> => invoke<readonly Preset[]>("list_presets"),
  loadSettings: (): Promise<SettingsDocument> => invoke<SettingsDocument>("load_settings"),
  saveSettings: (settings: SettingsDocument): Promise<void> => invoke<void>("save_settings", { settings }),
  saveProxy: (proxy: ProxySettings): Promise<ProxySettings> => invoke<ProxySettings>("save_proxy", { proxy }),
  createPreset: (preset: Preset): Promise<Preset> => invoke<Preset>("create_preset", { preset }),
  updatePreset: (preset: Preset): Promise<Preset> => invoke<Preset>("update_preset", { preset }),
  deletePreset: (presetId: string): Promise<void> => invoke<void>("delete_preset", { presetId }),
  providerStatus: (providerId: string): Promise<VisionCapabilities> => invoke<VisionCapabilities>("provider_status", { providerId }),
  credentialStatus: (providerId: string): Promise<boolean> => invoke<boolean>("credential_status", { providerId }),
  refreshModels: (provider: ProviderConfig): Promise<readonly VisionModel[]> => invoke<readonly VisionModel[]>("refresh_models", { provider }),
  setCredential: (providerId: string, secret: string): Promise<void> => invoke<void>("set_credential", { providerId, secret }),
  deleteCredential: (providerId: string): Promise<void> => invoke<void>("delete_credential", { providerId }),
  chatgptStatus: (): Promise<ChatGptStatus> => invoke<ChatGptStatus>("chatgpt_status"),
  chatgptSignIn: (): Promise<ChatGptStatus> => invoke<ChatGptStatus>("chatgpt_sign_in"),
  chatgptCancelSignIn: (): Promise<void> => invoke<void>("chatgpt_cancel_sign_in"),
  chatgptSignOut: (): Promise<void> => invoke<void>("chatgpt_sign_out"),
  chatgptModels: (): Promise<readonly VisionModel[]> => invoke<readonly VisionModel[]>("chatgpt_models"),
  supergrokStatus: (): Promise<SuperGrokStatus> => invoke<SuperGrokStatus>("supergrok_status"),
  supergrokBeginSignIn: (): Promise<DeviceCode> => invoke<DeviceCode>("supergrok_begin_sign_in"),
  supergrokFinishSignIn: (): Promise<SuperGrokStatus> => invoke<SuperGrokStatus>("supergrok_finish_sign_in"),
  supergrokCancelSignIn: (): Promise<void> => invoke<void>("supergrok_cancel_sign_in"),
  supergrokSignOut: (): Promise<void> => invoke<void>("supergrok_sign_out"),
  supergrokModels: (): Promise<readonly VisionModel[]> => invoke<readonly VisionModel[]>("supergrok_models"),
  savePngCopy: (request: SaveRequest): Promise<string> => invoke<string>("save_png_copy", { request }),
} as const;
